# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Importing the dataset

In [2]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [3]:
df.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [5]:
df.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [6]:
X = df.values[:,:-1]
Y = df.values[:,-1]

In [7]:
X

array([[7.500e+01, 0.000e+00, 5.820e+02, ..., 1.000e+00, 0.000e+00,
        4.000e+00],
       [5.500e+01, 0.000e+00, 7.861e+03, ..., 1.000e+00, 0.000e+00,
        6.000e+00],
       [6.500e+01, 0.000e+00, 1.460e+02, ..., 1.000e+00, 1.000e+00,
        7.000e+00],
       ...,
       [4.500e+01, 0.000e+00, 2.060e+03, ..., 0.000e+00, 0.000e+00,
        2.780e+02],
       [4.500e+01, 0.000e+00, 2.413e+03, ..., 1.000e+00, 1.000e+00,
        2.800e+02],
       [5.000e+01, 0.000e+00, 1.960e+02, ..., 1.000e+00, 1.000e+00,
        2.850e+02]])

In [8]:
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0.

In [9]:
X.shape

(299, 12)

In [10]:
Y.shape

(299,)

# Standardization

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X = sc.fit_transform(X)

print(X)

[[ 1.19294523e+00 -8.71104775e-01  1.65728387e-04 ...  7.35688190e-01
  -6.87681906e-01 -1.62950241e+00]
 [-4.91279276e-01 -8.71104775e-01  7.51463953e+00 ...  7.35688190e-01
  -6.87681906e-01 -1.60369074e+00]
 [ 3.50832977e-01 -8.71104775e-01 -4.49938761e-01 ...  7.35688190e-01
   1.45416070e+00 -1.59078490e+00]
 ...
 [-1.33339153e+00 -8.71104775e-01  1.52597865e+00 ... -1.35927151e+00
  -6.87681906e-01  1.90669738e+00]
 [-1.33339153e+00 -8.71104775e-01  1.89039811e+00 ...  7.35688190e-01
   1.45416070e+00  1.93250906e+00]
 [-9.12335403e-01 -8.71104775e-01 -3.98321274e-01 ...  7.35688190e-01
   1.45416070e+00  1.99703825e+00]]


# Train-Test Split

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X , Y, test_size = 0.3, random_state=100)

# Running Logistic Regression model

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)
Y_pred = classifier.predict(X_test)
print(list(zip(Y_test, Y_pred)))
print(classifier.coef_)
print(classifier.intercept_)

[(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 1.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.

# Performance Metrics

In [14]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print ("Classification report")

print (classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)

print ("Accuracy of the model:", acc*100)


[[55  4]
 [11 20]]
Classification report
              precision    recall  f1-score   support

         0.0       0.83      0.93      0.88        59
         1.0       0.83      0.65      0.73        31

    accuracy                           0.83        90
   macro avg       0.83      0.79      0.80        90
weighted avg       0.83      0.83      0.83        90

Accuracy of the model: 83.33333333333334


In [15]:
y_pred_prob = classifier.predict_proba(X_test)
print(y_pred_prob)

[[0.98954827 0.01045173]
 [0.73587974 0.26412026]
 [0.98487369 0.01512631]
 [0.98827353 0.01172647]
 [0.78159787 0.21840213]
 [0.13357866 0.86642134]
 [0.6964215  0.3035785 ]
 [0.89391539 0.10608461]
 [0.42887602 0.57112398]
 [0.94541693 0.05458307]
 [0.61575957 0.38424043]
 [0.72697061 0.27302939]
 [0.97044449 0.02955551]
 [0.92888684 0.07111316]
 [0.93363215 0.06636785]
 [0.10400828 0.89599172]
 [0.9605307  0.0394693 ]
 [0.96040855 0.03959145]
 [0.0456696  0.9543304 ]
 [0.99776411 0.00223589]
 [0.62880831 0.37119169]
 [0.88262301 0.11737699]
 [0.4639566  0.5360434 ]
 [0.9628672  0.0371328 ]
 [0.87318579 0.12681421]
 [0.95624391 0.04375609]
 [0.87333719 0.12666281]
 [0.98917787 0.01082213]
 [0.52864985 0.47135015]
 [0.74071068 0.25928932]
 [0.99346978 0.00653022]
 [0.98034942 0.01965058]
 [0.36124475 0.63875525]
 [0.65978275 0.34021725]
 [0.70907395 0.29092605]
 [0.52335746 0.47664254]
 [0.99040495 0.00959505]
 [0.80098271 0.19901729]
 [0.22096384 0.77903616]
 [0.8613344  0.1386656 ]


# Modelling Decision Tree

In [16]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10)#,min_samples_leaf=5,max_depth=10

#fit the model on the Data and predict the values
model_DecisionTree.fit(X_train,Y_train)

"""
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best/random')
"""

"\nDecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,\n                       max_features=None, max_leaf_nodes=None,\n                       min_impurity_decrease=0.0, min_impurity_split=None,\n                       min_samples_leaf=1, min_samples_split=2,\n                       min_weight_fraction_leaf=0.0, presort=False,\n                       random_state=10, splitter='best/random')\n"

In [17]:
Y_pred=model_DecisionTree.predict(X_test)
print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1.
 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
[(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 1.0), (1.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 1.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 1.0), (0.0, 1.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (0.0

In [18]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print ("Classification report")

print (classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)

print ("Accuracy of the model:", acc*100)


[[53  6]
 [14 17]]
Classification report
              precision    recall  f1-score   support

         0.0       0.79      0.90      0.84        59
         1.0       0.74      0.55      0.63        31

    accuracy                           0.78        90
   macro avg       0.77      0.72      0.74        90
weighted avg       0.77      0.78      0.77        90

Accuracy of the model: 77.77777777777779


# Prediction using Extra Tree Classifier

In [19]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import ExtraTreesClassifier
 
model=ExtraTreesClassifier(100,random_state=10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)
 
Y_pred=model.predict(X_test)
 

In [20]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print ("Classification report")

print (classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)

print ("Accuracy of the model:", acc*100)


[[57  2]
 [11 20]]
Classification report
              precision    recall  f1-score   support

         0.0       0.84      0.97      0.90        59
         1.0       0.91      0.65      0.75        31

    accuracy                           0.86        90
   macro avg       0.87      0.81      0.83        90
weighted avg       0.86      0.86      0.85        90

Accuracy of the model: 85.55555555555556


# Predictions using Random Forest Classifier

In [21]:
 
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier
 
model_RandomForest=RandomForestClassifier(n_estimators=101,random_state=10)
 
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
 
Y_pred=model_RandomForest.predict(X_test)

In [22]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print ("Classification report")

print (classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)

print ("Accuracy of the model:", acc*100)


[[56  3]
 [11 20]]
Classification report
              precision    recall  f1-score   support

         0.0       0.84      0.95      0.89        59
         1.0       0.87      0.65      0.74        31

    accuracy                           0.84        90
   macro avg       0.85      0.80      0.81        90
weighted avg       0.85      0.84      0.84        90

Accuracy of the model: 84.44444444444444


# Predictions using AdaBoost Classifier

In [23]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import AdaBoostClassifier
 
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(),
                                  n_estimators=10,
                                  random_state=10)
#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)

In [24]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print ("Classification report")

print (classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)

print ("Accuracy of the model:", acc*100)


[[53  6]
 [15 16]]
Classification report
              precision    recall  f1-score   support

         0.0       0.78      0.90      0.83        59
         1.0       0.73      0.52      0.60        31

    accuracy                           0.77        90
   macro avg       0.75      0.71      0.72        90
weighted avg       0.76      0.77      0.76        90

Accuracy of the model: 76.66666666666667


# Predictions using Gradient Boosting

In [25]:
#predicting using the Gradient_Boosting_Classifier
from sklearn.ensemble import GradientBoostingClassifier
 
model_GradientBoosting=GradientBoostingClassifier(n_estimators=270,
                                                  random_state=10)
 
#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)
 
Y_pred=model_GradientBoosting.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print ("Classification report")

print (classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)

print ("Accuracy of the model:", acc*100)


[[54  5]
 [11 20]]
Classification report
              precision    recall  f1-score   support

         0.0       0.83      0.92      0.87        59
         1.0       0.80      0.65      0.71        31

    accuracy                           0.82        90
   macro avg       0.82      0.78      0.79        90
weighted avg       0.82      0.82      0.82        90

Accuracy of the model: 82.22222222222221


## Ensemble Model 

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
 
# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1))

model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))

model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))

model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
estimators.append(('knn', model4))
 
# create the ensemble model

ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [28]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
cfm = confusion_matrix(Y_test, Y_pred)
print(cfm)

print ("Classification report")

print (classification_report(Y_test, Y_pred))

acc = accuracy_score(Y_test, Y_pred)

print ("Accuracy of the model:", acc*100)


[[56  3]
 [15 16]]
Classification report
              precision    recall  f1-score   support

         0.0       0.79      0.95      0.86        59
         1.0       0.84      0.52      0.64        31

    accuracy                           0.80        90
   macro avg       0.82      0.73      0.75        90
weighted avg       0.81      0.80      0.79        90

Accuracy of the model: 80.0


In [29]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(n_components = None)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_    #provie us the Eigen values
print(explained_variance)  #[0.72908626 0.22643525 0.03935829 0.00512019]  nut we dont know thic varble is this belong to.

[0.14448929 0.13686856 0.11507235 0.08969845 0.08700071 0.07455907
 0.07388457 0.07205403 0.05651353 0.05527437 0.05356264 0.04102245]


In [31]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.75)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.14448929 0.13686856 0.11507235 0.08969845 0.08700071 0.07455907
 0.07388457 0.07205403]


In [32]:
# Fitting SVC to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel="rbf",gamma=0.1,C=1)
classifier.fit(X_train, Y_train)
# Predicting the Test set results
Y_pred = classifier.predict(X_test)


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[54  5]
 [11 20]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.83      0.92      0.87        59
         1.0       0.80      0.65      0.71        31

    accuracy                           0.82        90
   macro avg       0.82      0.78      0.79        90
weighted avg       0.82      0.82      0.82        90

Accuracy of the model:  0.8222222222222222
